# SUPERVISED LEARNING

** REGRESSION PROBLEMS : **

**Linear Regression **

In [1]:
from sklearn import datasets
from sklearn.linear_model import LinearRegression as lr
from sklearn.cross_validation import train_test_split
import numpy as np

C:\Users\user\anaconda_new\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
db = datasets.load_diabetes()

In [61]:
X = db.data
y = db.target

In [62]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.4)

In [63]:
linreg = lr()
linreg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [64]:
linreg.score(X_test,y_test)

0.39372633366056597

In [7]:
linreg.intercept_

150.39286797321526

In [8]:
linreg.residues_

# Distance between predicted value and true value.

C:\Users\user\anaconda_new\lib\site-packages\sklearn\utils\deprecation.py:70: DeprecationWarning: Function residues_ is deprecated; ``residues_`` is deprecated and will be removed in 0.19
  warnings.warn(msg, category=DeprecationWarning)


763072.59309216647

In [65]:
y_pred = linreg.predict(X_test)

In [10]:
np.corrcoef(y_test,y_pred)

array([[ 1.        ,  0.66127029],
       [ 0.66127029,  1.        ]])

In [11]:
np.mean((y_test-y_pred)**2)

3022.2821742728856

In [12]:
linreg.coef_

array([   91.46520702,  -278.0962094 ,   614.49589331,   342.26524183,
       -1171.6152089 ,   676.93107252,   388.51486151,   440.53864026,
         881.7868287 ,    -9.13691844])

** Logistic Regression**

Using the same diabetes set from the previous linear regression problem

In [13]:
from sklearn.linear_model import LogisticRegression as logreg

In [14]:
logr = logreg(C=100,fit_intercept= False,n_jobs=-1,penalty='l1')

In [15]:
#logr = logreg()
logr.fit(X_train,y_train)

LogisticRegression(C=100, class_weight=None, dual=False, fit_intercept=False,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=-1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [16]:
y_pred = logr.predict(X_test)

In [17]:
np.corrcoef(y_test,y_pred)

array([[ 1.        ,  0.44858913],
       [ 0.44858913,  1.        ]])

In [18]:
logr.C

100

In [19]:
logr.penalty

'l1'

In [76]:
logr.decision_function(y_test[:10])

C:\Users\user\anaconda_new\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[ -138.40895994,   195.48415858,   -68.91976304,  -387.14488641,
          182.7562695 ,  -327.60991346,   401.29581195,   428.67338024,
          299.65917628,  -475.87627013,   145.68859641,   288.26115271,
         -594.88023942,   159.93333123,  -520.81062279,  -162.95090073,
          230.95963511,   687.27672802,  -220.5198318 ,   199.14188749,
         -105.82447609,   529.16037958,    11.88243588,    57.45901527,
         -673.05733217,  -215.92965852,  -478.05895679,  -217.31009907,
         -143.39156738,   113.32410927,  -669.1995199 ,   416.99630027,
         -528.70298451,    49.34421454,   128.06573528,   205.57469262,
          -47.59234352,   611.93593362,  -794.69143118,  -465.61375984,
          615.57403315,   254.7245184 ,   -50.52119318,  -214.7325655 ,
         -166.15223168,    44.53539212,  -161.95930656,   -26.87970201,
         -336.09168676, -1062.76441623,   939.01326407,   126.88341402,
         -309.76384507,   -91.68882316,  -263.26517593,   130.45

In [21]:
logr.get_params(deep = True)

{'C': 100,
 'class_weight': None,
 'dual': False,
 'fit_intercept': False,
 'intercept_scaling': 1,
 'max_iter': 100,
 'multi_class': 'ovr',
 'n_jobs': -1,
 'penalty': 'l1',
 'random_state': None,
 'solver': 'liblinear',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [22]:
logr.set_params(C = 1,penalty = 'l2')

LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=False,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=-1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [23]:
logr.predict_log_proba(y_pred[:10])

C:\Users\user\anaconda_new\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\user\anaconda_new\lib\site-packages\sklearn\linear_model\base.py:352: RuntimeWarning: overflow encountered in exp
  np.exp(prob, prob)
C:\Users\user\anaconda_new\lib\site-packages\sklearn\linear_model\logistic.py:1306: RuntimeWarning: divide by zero encountered in log
  return np.log(self.predict_proba(X))


array([[         -inf,          -inf,          -inf, -655.99464741,
        -566.14122717,          -inf, -439.34147562, -403.121284  ,
                 -inf,          -inf,          -inf, -171.18701543,
                 -inf,          -inf,          -inf,          -inf,
                 -inf, -151.4643032 ,          -inf,          -inf,
                 -inf,          -inf,          -inf,          -inf,
                 -inf,          -inf,          -inf,          -inf,
                 -inf,          -inf,          -inf,          -inf,
                 -inf,          -inf,          -inf, -624.25087932,
        -656.27162929, -447.33224391,          -inf,          -inf,
        -483.81896097, -640.79991406,          -inf,          -inf,
                 -inf,          -inf,          -inf, -690.81692189,
                 -inf,          -inf, -387.88883097,          -inf,
                 -inf,          -inf,          -inf, -626.53299376,
                 -inf,          -inf,          -

In [24]:
logr.predict_proba(X)

array([[ 0.00564477,  0.00561   ,  0.0056467 , ...,  0.00590153,
         0.0058698 ,  0.00582643],
       [ 0.00568586,  0.0058354 ,  0.00565474, ...,  0.00552543,
         0.00568999,  0.00562263],
       [ 0.00560615,  0.0056614 ,  0.00562707, ...,  0.00584361,
         0.00594796,  0.00579901],
       ..., 
       [ 0.00563933,  0.00562446,  0.00572536, ...,  0.00572792,
         0.00573183,  0.00548482],
       [ 0.00570348,  0.00560776,  0.00558116, ...,  0.00560733,
         0.00564969,  0.00583345],
       [ 0.00554296,  0.0058144 ,  0.00553973, ...,  0.00546044,
         0.00537665,  0.00563454]])

** Support Vector Machine **

In [25]:
from sklearn import svm

In [26]:
iris = datasets.load_iris()
X = iris.data
y = iris.target
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 4)

In [27]:
sv = svm.SVC()
sv.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [28]:
y_pred = sv.predict(X_test)

In [29]:
sv = svm.SVC(C=100,decision_function_shape='ovr',kernel='rbf',gamma= None,probability=True,shrinking=True)

In [30]:
sv.get_params

<bound method BaseEstimator.get_params of SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=None, kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)>

In [31]:
sv.decision_function_shape

'ovr'

In [32]:
sv.set_params(probability = True)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=None, kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [33]:
X_train.shape,y_train.shape

((112, 4), (112,))

In [34]:
np.corrcoef(y_pred,y_test)

array([[ 1.        ,  0.98383844],
       [ 0.98383844,  1.        ]])

In [35]:
sv.tol

0.001


** CLASSIFICATION **

**KNeighborsClassification**

In [36]:
from sklearn.neighbors import KNeighborsClassifier as knc

In [37]:
knn = knc(n_neighbors=5,weights = 'distance',n_jobs= -1)

In [38]:
knn.n_jobs

-1

In [39]:
knn.algorithm

'auto'

In [40]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
           weights='distance')

In [41]:
a = knn.predict(X)

In [42]:
np.corrcoef(a,y)

array([[ 1.,  1.],
       [ 1.,  1.]])

In [77]:
knn.outputs_2d_

False

In [44]:
knn.kneighbors_graph(X).toarray()

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  1.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

# UNSUPERVISED LEARNING

**CLUSTERING**

**KMeans Clustering Algorithm**

In [45]:
from sklearn.cluster import KMeans

In [46]:
z = np.array([[1,3],[2,4],[2,3],[2,4],
            [5,5],[5,4],[6,1],[4,6]])
kmeans = KMeans(n_clusters = 2)
kmeans.fit(z)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [47]:
kmeans.predict([1,8])

C:\Users\user\anaconda_new\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])

In [48]:
kmeans.cluster_centers_

array([[ 5.  ,  4.  ],
       [ 1.75,  3.5 ]])

In [49]:
np.std(z)

1.5799030824705673

In [50]:
kmeans.transform(z)

array([[ 4.12310563,  0.90138782],
       [ 3.        ,  0.55901699],
       [ 3.16227766,  0.55901699],
       [ 3.        ,  0.55901699],
       [ 1.        ,  3.57945527],
       [ 0.        ,  3.28823661],
       [ 3.16227766,  4.93077073],
       [ 2.23606798,  3.36340601]])

In [51]:
kmeans.fit_predict([[5,6],[5,7],[7,5],[9,6]])

array([1, 1, 0, 0])

In [52]:
kmeans.cluster_centers_

array([[ 8. ,  5.5],
       [ 5. ,  6.5]])

In [53]:
kmeans.transform(z)

array([[ 7.43303437,  5.31507291],
       [ 6.18465844,  3.90512484],
       [ 6.5       ,  4.60977223],
       [ 6.18465844,  3.90512484],
       [ 3.04138127,  1.5       ],
       [ 3.35410197,  2.5       ],
       [ 4.9244289 ,  5.59016994],
       [ 4.03112887,  1.11803399]])

In [54]:
kmeans.transform([[1,1],[2,2]])

array([[ 8.32165849,  6.80073525],
       [ 6.94622199,  5.40832691]])

In [55]:
kmeans.cluster_centers_

array([[ 8. ,  5.5],
       [ 5. ,  6.5]])

In [56]:
kmeans.inertia_

3.0

In [57]:
kmeans.init

'k-means++'

In [58]:
kmeans.labels_

array([1, 1, 0, 0])

In [59]:
kmeans.score(z),kmeans.inertia_

(-114.0, 3.0)